### ISSUE TITLE
Convert `max-width` 100vh to `max-height` 100vh for images

### ISSUE THREAD

**Issue by Bigguysahaj** [whole-earth/campus-explore#1]
The images appear stretched out and long throughout.

**Comment by whole-earth** [comment]
+1. Also, add styling property `image-fit: cover`
([image-fit: cover MDN doc](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit#cover))

**Comment by Bigguysahaj** [comment]
> +1. Also, add `aspect-ratio: 4 / 3` and `image-fit: cover` to standardize sizing of images regardless of native dimensions. ([MDN: `image-fit: cover`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit#cover)) ([MDN: `aspect-ratio`](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio))

Issue was only related to chrome and hence it slipped my eyes. Have to keep that in mind to check for from now onwards as I use firefox.

I'm using object-cover ( `object-fit: cover') and `width : auto` and `height : 100%` which seems to work for the image on both ends, along with that using `padding : 8px` to add space around

```js
   <img 
      alt= "image" 
      className="p-2 w-auto h-full object-cover"
      src= {image.url}
    />
``` 

chrome:
![image](https://github.com/whole-earth/campus-explore/assets/70798888/d1941977-20ec-4dec-96e7-065307b74890)


firefox: 
![image](https://github.com/whole-earth/campus-explore/assets/70798888/d81fb071-3e1f-4eb0-827a-f5ed9226d9f0)

**Comment by Bigguysahaj** [comment]
I'm closing this issue now
